### ISSUE TITLE
How to use this package in a controller?

### ISSUE THREAD

**Issue by xchimx** [MahdiMajidzadeh/Laravel-Unsplash#3]
I create a new Controller:

`    public function getMedia()
    {
                $text = Input::get('getmedia');
		
		$unsplash  = new MahdiMajidzadeh\LaravelUnsplash\Search();
		$photos     = $unsplash->photo($text)->get();
	
	return view('mediacreator', compact('photos'));`

But get the Error:

`Class 'App\Http\Controllers\MahdiMajidzadeh\LaravelUnsplash\Search' not found`

In Routes the same Code works.
How can i fix that, thank you.

**Comment by MahdiMajidzadeh** [comment]
use must use
`$unsplash  = new \MahdiMajidzadeh\LaravelUnsplash\Search();`

**Comment by xchimx** [comment]
It works, thank you!
